import { NextRequest, NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';
import { HttpError } from '@/lib/http';

export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ token: string }> }
) {
  try {
    const { token } = await params;

    if (!token) {
      throw new HttpError(400, 'Share token is required');
    }

    // Find the share record
    const share = await prisma.reportShare.findUnique({
      where: { token },
      include: {
        report: {
          select: {
            id: true,
            headline: true,
            mdContent: true,
            format: true,
          },
        },
        project: {
          select: {
            name: true,
          },
        },
      },
    });

    if (!share) {
      throw new HttpError(404, 'Share not found');
    }

    // Check if share has expired
    if (share.expiresAt && share.expiresAt < new Date()) {
      throw new HttpError(410, 'Share link has expired');
    }

    // Check if download is allowed
    if (!share.allowDownload) {
      throw new HttpError(403, 'Download not allowed for this report');
    }

    // Generate a simple PDF content (in a real implementation, you'd use a proper PDF library)
    const pdfContent = generateSimplePDF(share.report.mdContent, share.report.headline, share.project.name);

    // Return the PDF as a downloadable file
    return new NextResponse(pdfContent, {
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="${share.project.name} - ${share.report.headline}.pdf"`,
      },
    });
  } catch (error: any) {
    console.error('Error downloading shared report:', error);
    if (error instanceof HttpError) {
      return NextResponse.json(
        { error: error.message },
        { status: error.statusCode }
      );
    }
    return NextResponse.json(
      { error: 'Failed to download report' },
      { status: 500 }
    );
  }
}

function generateSimplePDF(content: string, title: string, projectName: string): Buffer {
  // This is a very basic placeholder for PDF generation
  // In a real implementation, you'd use a library like Puppeteer or jsPDF

  const html = `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8">
      <title>${title}</title>
      <style>
        body {
          font-family: Arial, sans-serif;
          line-height: 1.6;
          color: #333;
          max-width: 800px;
          margin: 0 auto;
          padding: 40px 20px;
        }
        .header {
          text-align: center;
          margin-bottom: 40px;
          border-bottom: 2px solid #e5e7eb;
          padding-bottom: 20px;
        }
        .header h1 {
          margin: 0;
          color: #1f2937;
          font-size: 28px;
        }
        .header p {
          margin: 10px 0 0 0;
          color: #6b7280;
          font-size: 16px;
        }
        .content {
          margin-bottom: 40px;
        }
        .content h1, .content h2, .content h3 {
          color: #1f2937;
          margin-top: 2em;
          margin-bottom: 1em;
        }
        .content h1 { font-size: 24px; }
        .content h2 { font-size: 20px; }
        .content h3 { font-size: 18px; }
        .content p {
          margin-bottom: 1em;
        }
        .content ul, .content ol {
          margin-bottom: 1em;
          padding-left: 2em;
        }
        .content blockquote {
          border-left: 4px solid #e5e7eb;
          margin: 1em 0;
          padding-left: 1em;
          color: #6b7280;
        }
        .footer {
          text-align: center;
          margin-top: 40px;
          padding-top: 20px;
          border-top: 1px solid #e5e7eb;
          color: #6b7280;
          font-size: 12px;
        }
      </style>
    </head>
    <body>
      <div class="header">
        <h1>${title}</h1>
        <p>Generated by Nex-Intel for ${projectName}</p>
      </div>
      <div class="content">
        ${content.replace(/\n/g, '<br>')}
      </div>
      <div class="footer">
        <p>This report was generated by Nex-Intel - Evidence-first competitive intelligence.</p>
        <p>Generated on ${new Date().toLocaleDateString()}</p>
      </div>
    </body>
    </html>
  `;

  // Return the HTML as a buffer (in a real implementation, this would be converted to PDF)
  return Buffer.from(html, 'utf-8');
}